== El Diario de John Banks

Nací de padres honestos; el nombre de mi padre era William, y el de mi madre era Emme.
Yo fui su único hijo.
Nací en Sunderland, en la parroquia de Issell, en el condado de Cumberland.
Mi padre, al no tener ningún bien propio adquirió algo de tierra para cultivarla.
Su oficio era curtidor^
footnote:[Uno que trabaja con cuero y pieles]
y también hacía guantes.
Algunos años después, se mudó cerca de la reunión de Pardshaw,
donde mis padres recibieron la verdad un tiempo después que yo,
y vivieron y murieron en ella, según sus medidas.
Pertenecí a esta reunión por más de cuarenta años.

Aunque mis padres no tenían muchas riquezas en este mundo, aun así,
de acuerdo con su capacidad y a la costumbre del condado en el que vivían,
me criaron bien y de forma disciplinada.
Ellos cuidadosamente me mantenían apartado de esos males
en los que los niños y jóvenes son propensos a caer,
especialmente mi querida madre, ya que ella era una mujer celosa de Dios.
El cuidarme de este modo tuvo un buen efecto en mí;
y asimismo lo tendrá (podemos contar con ello) en los hijos de
todos los que cumplan con su responsabilidad como padres debidamente;
de lo contrario, me temo que serán hallados culpables en el día de dar cuentas.

Fui inscrito en la escuela cuando tenía siete años y me mantuvieron allí hasta los catorce,
durante ese tiempo aprendí tanto el inglés como el latín, y podía escribir bien.
A los catorce años,
mi padre me puso a enseñar durante un año en una escuela en Dissington,
y después de eso en la Capilla de Mosser cerca de Pardshaw,
donde además les leía la Escritura y el sermón (así llamado)
a las personas que venían cada primer día de la semana,
y también cantaba salmos y oraba.
No me gustaba esta práctica, pero mi padre, junto con otras personas,
me persuadían a hacerlo.

Por este servicio,
recibía de las personas un salario de doce peniques al año por
cada una de las casas de los que iban a allá a escucharme,
también un vellón de lana, y mi comida gratis,
además de doce peniques trimestrales por cada uno de mis veinticuatro estudiantes.
Esta capilla era llamada la capilla de fácil acceso, porque la casa del campanario^
footnote:[Los antiguos Amigos usaban la frase casa del campanario
para referirse a los lugares grandes de reunión,
puesto que no estaban dispuestos a usar la palabra _iglesia_
para referirse a un edificio de madera y piedra.]
de la parroquia estaba a algunas millas de distancia.
Entre otras personas que no les importaba asistir a este o a otro lugar de culto,
vino un tal John Fletcher, un gran erudito, pero un borracho.
Un día me llamó aparte, y me dijo que leía muy bien para ser tan joven,
pero que no oraba según la forma prescrita como lo hacían otros,
y dijo que me enviaría una carta para enseñarme cómo orar, lo cual hizo.

Cuando esta carta llegó, salí de la capilla y la leí; y cuando terminé de leerla,
fui convencido de que estaba mal por la luz del Señor Jesús,
que inmediatamente me reveló las palabras del apóstol Pablo acerca del
Evangelio que se le había dado para predicar--que "`no lo recibió,
ni lo aprendió de hombre alguno, sino por revelación de Jesucristo.`"^
footnote:[Gálatas 1:12]
En respuesta a esto surgieron dentro de mí las siguientes palabras:
"`¡Pero tú recibiste esta oración de un hombre,
y estás siendo enseñado a orar por un hombre, y de paso uno de los peores entre muchos!`"
Entonces el temor del Señor cayó sobre mí,
con el cual fui golpeado en lo profundo de mi corazón, y dije dentro de mí:
"`Nunca oraré de esta manera.`"
Entonces me fue revelado lo siguiente:
"`Ve a la reunión del pueblo que en desdén es llamado Cuáqueros,
porque ellos son el pueblo de Dios.`"
Así que fui a la reunión de Pardshaw al siguiente primer día.

Esto sucedió cerca del fin de año,
cuando estaba a punto de recibir el pago de las personas
por los servicios que había realizado.
Pero no pude tomar nada de ellos, estando ahora convencido de que era malo,
ni volví jamás a leer nada en la capilla.

Justo antes de este tiempo, cuando tenían como dieciséis años,
en el décimo mes del año 1654,
le plació al Señor alcanzar mi corazón y mi conciencia por Su Espíritu puro y vivo,
mediante Su bendita aparición en y a través de Jesucristo,
por medio de lo cual recibí el conocimiento de Dios y del camino de Su bendita verdad,
estando solo en el campo, antes de haber oído predicar a un Cuáquero,
o de haber estado en alguna de sus reuniones.
Pero la primera vez que asistí a una de ellas (que fue en Pardshaw, como antes mencioné),
el Poder del Señor cayó tan fuertemente sobre mí,
que fui llevado a clamar en la amargura de mi alma,
experimentando una verdadera visión y sentido de mis pecados,
que se mostraron sobremanera pecaminosos.
Y entonces, el mismo día en la noche,
cuando iba camino a una reunión del pueblo de Dios que en desdén es llamado Cuáqueros,
fui golpeado y llevado hasta el suelo por el peso del juicio de Dios que
había caído fuertemente sobre mí a causa del pecado y la iniquidad,
y dos amigos tuvieron que levantarme.
¡Oh,
la tristeza piadosa que se apoderó de mí esa noche durante la reunión! En verdad pensaba
dentro de mí que todos estaban en una condición mejor que la mía. Un amigo,
que se conmovió por el sentido de mi condición y que sintió gran compasión por mí,
fue movido a leer un escrito en esta reunión,
que fue tan adecuado para mi condición que me ayudó un poco,
y le dio algo de reposo a mi espíritu.

En ese entonces me sentía muy oprimido y perplejo,
teniendo mis pecados puestos en orden delante de mí. El
tiempo que había gastado en desenfreno y ligereza,
fuera del temor de Dios, en vanidad, deportes y pasatiempos,
vino a mi memoria y fue puesto ante mis ojos.
El libro de mi conciencia fue abierto,
porque había sido desenfrenado y ligero por naturaleza.
Y aunque muchas veces se habían despertado buenos deseos en mí,
y algo dentro de mí me juzgaba y reprendía,
a menudo contendiendo conmigo para apartarme del mal, aun así, al no saber qué era esto,
llegué a callarlo y a levantarme sobre ello.
Sí,
yo era como aquellos que se regocijaron sobre el
testigo de Dios después de haberlo asesinado,^
footnote:[Apocalipsis 11:10]
a saber, el testigo y testimonio de Su Espíritu Santo,
en y a través de Jesucristo Su Hijo,
que por el gran amor de Dios es revelado a los hijos e hijas de los hombres.
Este era el Espíritu mediante el cual el Señor muchas veces contendió conmigo,
hasta que finalmente Él triunfó sobre mí. De modo que puedo decir,
como un verdadero testigo a favor de Dios,
y de la suficiencia de Su poder y de Su Espíritu vivificante: Yo no solo fui convencido,
por la aparición viva del Señor Jesús, de la vanidad,
pecado e iniquidad del mundo (de cuyas cosas participé),
sino que al someterme a Su aparición con vigilancia y temor,
llegué a una experiencia perceptible de Su obra en mi corazón,
subyugando y derribando la naturaleza desenfrenada en mí,
y lavándome y limpiándome del pecado y la corrupción,
a fin de que fuera verdaderamente transformado y convertido.

Pero antes de llegar a experimentar esta obra realizada ¡oh,
los días y noches de tristeza piadosa y de dolor espiritual
por los que tuve que pasar durante algunos años!
El trato bajo el cual estaba fue tan duro, tanto para mi cuerpo como para mi mente,
que dejé de enseñar en la escuela, lo cual, aunque era bueno y lícito, sin embargo,
no era adecuado para mí en la condición en la que me encontraba.
Me puse a aprender el oficio de mi padre, junto con algo de agricultura,
lo cual hacía con diligencia; y viví con mis padres,
quienes un tiempo después recibieron la verdad,
lo cual fue un motivo de mucha alegría para mi alma.

A medida que viajaba bajo el ministerio de condenación
y de juicio a causa del pecado y la transgresión,
tenía una guerra muy grande contra el enemigo de mi alma, el cual,
a través de su sutileza, trataba de desviarme de la sencillez de la verdad,
y llevarme a la desesperación,
al hacerme pensar que ya no había misericordia para mí. Sin embargo,
en una medida pequeña, yo sabía que el Señor me había mostrado misericordia,
la cual mezcló con juicio debido a mis muchos pecados pasados.
Pero la experiencia que había obtenido a través de la aflicción de mi alma,
y la fe que Dios había engendrado en mi corazón,
me fortalecieron para resistir al enemigo y sus razonamientos sutiles.
Vencí al maligno mediante una diligente espera en la luz,
y al mantenerme constantemente cerca del poder de Dios,
esperando en Él en silencio junto a Su pueblo, en cuya práctica mi alma se deleitaba.

¡Oh, el refrigerio y la consolación divina del que fuimos partícipes en aquellos días!
Y cómo disfrutamos los unos de los otros, y nos sentimos cercanos y queridos,
en el sentido y experiencia interior del poder y presencia del Señor con nosotros.
Pero fue a través de diversas pruebas y de profundos tratos, con temor y temblor,
que llegamos a ser hechos partícipes de estas cosas.
En verdad, benditos y felices aquellos que saben lo que la verdad les ha costado,
y la sostienen en justicia.

Al esperar diligentemente en la luz,
y mantenerme cerca del poder de Dios que es recibido en ella,
llegué a experimentar la obra de Su poder avanzando en mi corazón,
la cual continuaba y prosperaba gradualmente dentro de mí,
y cuyo fin era efectuar mi libertad de la esclavitud.
Y así ganaba cada vez más terreno contra el enemigo de mi alma,
por medio de la fe en ese poder sin el cual no se puede obtener ninguna victoria.
Y siempre encontraba que mi prosperidad en la verdad venía a través
de la fidelidad al Señor en cualquier cosa que Él manifestara,
aunque fuera en la cosa más pequeña. Porque la infidelidad en las
cosas pequeñas es la razón por la que muchos experimentan grandes
pérdidas y heridas en su crecimiento en la verdad.

Después de haber pasado por mucha tribulación,
y de llorar y lamentarme solo en bosques y lugares solitarios,
donde a menudo deseaba estar, llegué a sentir más estabilidad en mi espíritu,
y la paz comenzó a brotar en mi alma, donde la angustia y el dolor habían estado.
En aquel entonces,
hubo momentos en los que estaba listo para pensar que jamás volvería a experimentar
tales combates y asaltos del enemigo de mi alma como los que ya había atravesado.
Pero mientras más aumentaba mi experiencia de los tratos del Señor conmigo,
más se disfrazaba el enemigo;^
footnote:[2 Corintios 11:14-15]
y cuando no podía vencer mediante sus primeros disfraces, entonces, en su sutileza,
inventaba nuevos.
Así llegué a ver claramente que no era seguro para
mí descansar satisfecho con lo que ya había atravesado,
o conformarme con la victoria que ya había obtenido,
sino que tenía que seguir viajando en fe y paciencia,
y velar diligentemente en la luz de Jesucristo,
donde siempre se recibe el verdadero poder.
Porque a pesar de las muchas veces que el Señor me libró,
y de la fuerza y victoria que había experimentado, al Señor,
de acuerdo con la grandeza de Su sabiduría,
le parecía bien hacerme sensible de mi propia debilidad,
y de que no había ninguna fuerza para estar firme, ni ningún lugar seguro para mí,
en el cual pudiera permanecer, salvo en Su poder; y bajo el sentido de esto,
era humillado, reducido y llevado al polvo.

Por lo tanto, tomé la siguiente resolución seria delante de Dios en Su temor:
"`Confiaré en la suficiencia de Tu poder, oh Señor, por siempre.`"
Alrededor de seis años después de haber recibido la verdad,
a través de grandes ejercicios y tristeza piadosa,
llegué a ser establecido en el poder de Dios,
y a tener sustancia en mi espíritu por medio de él. Tuve algunas revelaciones
del Espíritu de la Verdad mientras esperaba silenciosamente en el Señor,
lo cual tendía a ministrar consuelo y satisfacción a mi alma,
sintiendo una experiencia renovada de los tratos del Señor conmigo,
y entonces el Señor abrió mi boca con un testimonio
que procedía del brote fresco de la vida,
el cual debía predicarles a Sus hijos y pueblo.
Pero oh, la gran batalla que entonces tenía a causa de los razonamientos,
sugiriendo que no era más que un niño, y que otros eran más capaces y aptos para hablar.
Pero el Señor, por Su poder, me llevó a sentirme dispuesto, y por fin,
con temor y temblor hablé en nuestras benditas reuniones.

En una oportunidad,
cuando estaba sentado esperando en silencio en el
Señor en una reunión de Amigos en Pardshaw Crag,
cayó sobre mi espíritu un fuerte ejercicio,
en el cual se reveló dentro de mí que debía ir a la casa del campanario en Cockermouth,
y fue difícil para mí ceder a esto.
Pero el Señor, por Su Poder, me hizo estremecer y temblar,
y con ello me hizo estar dispuesto a ir.
Pero entonces, cuando había cedido, deseaba saber qué era lo que tenía que hacer allí,
lo cual fue la razón por la que, durante un poco de tiempo,
fui encerrado en mí mismo y estaba en una medida de oscuridad.
Entonces clamé al Señor, y le dije que si era Su voluntad que fuera,
me entregaría a ella; y siendo sensible de que lo era,
fui en fe y quietud de mente y espíritu.

Cuando estaba en camino, tuve una experiencia,
en la que por un momento me pareció que el sacerdote estaba en pie ante mí,
y fue revelado en mí decirle: "`Si tú eres un ministro de Cristo,
levántate a probar tu religión;
y si es la misma que la de los apóstoles y ministros de Cristo, en doctrina y práctica,
yo te reconoceré como un ministro; pero si no,
yo he sido enviado por Dios en este día para testificar contra ti.`"
Y apenas entré al lugar donde estaba predicando el sacerdote asalariado, George Larcum,
él gritó: "`¡Hay alguien que ha entrado a la iglesia como un loco,
con su sombrero en su cabeza! ¡Guardias de la iglesia, sáquenlo!`"
Porque él no podía predicar después de que entré a la casa del campanario.
Así que me echaron, como él se los había pedido.
Esto fue en el tiempo de Oliver Cromwell,
y no mucho después hubo un cambio de gobierno y el
sacerdote mismo fue expulsado de su puesto.
Un tiempo después de haber sido echado, fui movido por el Señor a entrar otra vez,
y Dios me dio fuerza para permanecer hasta que el sacerdote terminara;
pero su predicación fue pesada y confusa.
Entonces, con las palabras antes mencionadas, abrí mi boca en el temor del Señor,
lo cual hizo que el asalariado saliera tan rápido como pudo,
por una puerta diferente a la que normalmente usaba;
y entonces la gente formó un gran alboroto--algunos tratando de golpearme,
y otros tratando de evitar que me golpearan.

Cuando me arrastraron fuera de la casa,
fui capacitado por el poder de Dios para declarar la verdad en medio de la gente,
y también de mostrarles al engañador que estaban siguiendo.
Y habiendo obedecido los requerimientos del Señor,
salí de allí con una dulce paz y consuelo espiritual en mi corazón.

Un cierto día, estando en una reunión de Amigos sobre una colina, cerca de Coldbecke,
en Cumberland, George Fletcher de Hutton Hall, un juez de paz (así llamado),
entró a la reunión de una manera violenta,
cabalgando entre los Amigos que estaban sentados en el suelo,
y pisando con las patas de su caballo un vestido de mujer.
Fui movido por el Señor a arrodillarme en oración al frente de su caballo, y,
como un perverso perseguidor del pueblo de Dios,
me golpeó fuertemente en la cabeza y en la cara con el látigo de su caballo.
Cuando vio que no podía moverme,
le pidió a su siervo (que estaba cerca) que me sacara de su vista,
el cual vino con gran furia y me agarró por el cabello,
y me haló hacia abajo de la colina.
Pero me puse de pie, y le dije a su maestro: "`¿Tú pretendes ser un juez de paz,
y sin embargo rompes la paz, y disturbas, persigues y abusas del pueblo pacífico de Dios,
y pones a tu siervo a hacer lo mismo?`"
Y él dijo:
"`¡Tú sabrás que yo soy un juez de paz después de que acabe contigo!
¿No había ningún otro lugar que les sirviera para reunirse,
excepto en mi cara?`"
Sin embargo, esta reunión estaba muy lejos de su casa, en los ejidos.
Me envió a mí y a tres más a la cárcel común de Carlisle,
durante el tiempo en que estaba vigente esa acta que imponía
una multa de cinco libras por la primera ofensa;
diez libras por la segunda, y el destierro por la tercera.^
footnote:[En parte debido a la inestabilidad política de esos tiempos
y al miedo generalizado a los levantamientos armados contra el gobierno,
y en parte debido a la envidia e influencia de los ministros nacionales,
se promulgó una ley (llamada el Acta Contra Conventos Sediciosos)
que prohibía todas las reuniones religiosas de cinco o más personas,
aparte de las reuniones establecidas por la Iglesia de Inglaterra.]
Él ordenó que una vaca y un caballo, que valían seis libras y diez chelines,
fueran confiscados a mi padre (con quien vivía), por mi multa de cinco libras,
siendo esta la primera ofensa (según su juicio),
y además me mantuvo en prisión durante algunas semanas.

George Martin, un hombre impío y duro de corazón, siendo el carcelero,
nos metió en la prisión común por varios días y noches sin pan ni agua,
porque no podíamos satisfacer su deseo codicioso de darle ocho peniques por cada comida.
Entonces cuando nos metió en la cárcel común,
nos amenazó diciendo que quería ver cuánto tiempo
podíamos sobrevivir en ese lugar sin comida,
y no permitía que nadie nos ayudara,
ni que ninguno de nuestros amigos nos trajera algo para tener donde dormir,
ni siquiera un poquito de paja.
No teníamos donde acostarnos salvo en la ventana de la prisión, sobre las frías piedras,
porque la pared era gruesa, pero no había espacio sino para uno a la vez.
Y cuando vio que no podía lograr su objetivo, a pesar de su crueldad,
nos sacó de la cárcel común y nos metió en un cuarto
dentro de su propia vivienda en la cárcel,
donde mantenía prisioneros a varios Amigos por no pagar diezmos,
a demanda del antes mencionado George Fletcher.
El carcelero a menudo era cruel, impío y abusivo en su proceder con los Amigos;
pero en unos pocos años fue recompensado de acuerdo con sus obras,
porque él mismo fue echado en la prisión por deudas, y allí terminaron sus días.

Cuando las audiencias trimestrales comenzaron,
lo cual sucedió como dos semanas después de haber sido encarcelados en Carlisle,
fuimos llamados y examinados por Philip Musgrove, un hombre de la ciudad, llamado juez,
que sin embargo era un antiguo perseguidor, quien,
con una gran pretensión de amor hacia nosotros dijo que, si nosotros nos conformábamos,
y acudíamos a la iglesia nacional,
ellos nos concederían todo el favor que estuviera a su alcance.
Y cuando alguno de nosotros intentaba responder sus preguntas o propuestas, dijo:
"`Ustedes deben mantenerse en silencio, a menos de que quieran conformarse,
porque no pueden predicar aquí. Pero,`" dijo de forma burlona,
"`cuando sean desterrados más allá del mar,
entonces podrán predicar allá.`" Uno de nosotros respondió:
"`No tenemos miedo de ser desterrados más allá del mar; porque creemos,
y tenemos buenas razones para hacerlo, que el Señor nuestro Dios,
a quien nosotros adoramos y servimos,
y quien por Su gran poder nos ha preservado a todos hasta ahora en este lado del mar,
nos preservará también del otro lado,
si permanecemos fieles en nuestro testimonio de Él.`"

Fuimos puestos en libertad por el tribunal de esas sesiones,
después de habernos quitado bienes por nuestras multas; pero entonces,
el alguacil del condado, Willfrid Lawson, de Issel Hall, estando presente,
le dijo al carcelero: "`Si ellos no quieren pagar las cuotas,
póngalos en la prisión común otra vez, y déjenlos allí hasta que se pudran.`"
Entonces el carcelero nos puso en la cárcel común
otra vez porque no quisimos pagarle cuotas.
En ese momento había en la cárcel un hombre lunático, y cuatro con él por robo,
y dos ladrones de ganados muy conocidos, llamados Redhead y Wadelad,
y también una mujer por asesinar a su hijo.
Después de que las audiencias del tribunal habían terminado,
permitieron que varios familiares y conocidos de estas personas vinieran a visitarlos,
los cuales les dieron tanta bebida que casi todos estaban completamente borrachos;
y en la prisión, siendo un lugar muy pequeño y asqueroso,
abusaron tanto de sí mismos y de nosotros con su inmundicia,
que era suficiente como para casi abrumar a algunos de nosotros.
Al siguiente día, le hicimos saber al carcelero como habíamos sido abusados,
luego de lo cual le pidió al que tenía la llave que
nos llevara a la habitación donde estábamos antes,
diciendo que a él le desagradaba tenernos ahí, porque sabía que éramos hombres honestos,
dejando de lado nuestra religión. Uno de nosotros respondió: "`Si el fruto es bueno,
el árbol no puede ser malo.`"
Y un poco de tiempo después de haber estado en su casa, nos dio nuestra libertad,
sin que pagáramos cuotas.
Esto fue en el quinto mes del año 1663.

Lo siguiente es una carta que escribí cuando era prisionero en Carlisle.

Queridos Padres,

Por la presente, ustedes podrán ver que sigo fiel a mi deber como hijo,
y sentir mi dulce y tierno amor, tanto natural como espiritualmente,
extendido hacia ambos; y en la medida que sean fieles a lo que el Señor les ha revelado,
por Su luz pura, Él los guardará.

Queridos padres, puesto que ha sido determinado que yo sea llamado a padecer,
por ninguna otra razón más que adorar a Dios junto a Su pueblo,
deseo que estén contentos, y que no murmuren ni se quejen.
Mas bien, vivan en amor, quietud, y en completa unidad el uno con el otro,
para que la bendición del Señor esté sobre ustedes, y los haga prosperar en todo;
porque los que verdaderamente temen al Señor no tendrán falta de ningún bien.
Dejen que su fe permanezca aquí, queridos corazones,
y sean pacientes y estén contentos en sus mentes,
y no demasiado preocupados por mí y por mi bienestar.
Porque estoy convencido, sintiendo la evidencia de la Verdad en mi corazón,
de que no estoy padeciendo como malhechor,
sino por obedecer los requerimientos del Señor, sí,
por adorarlo y servirlo a Él en espíritu y en verdad.
Por lo tanto, me está yendo bien, y me seguirá yendo bien,
si me mantengo fiel hasta el final.
No se desanimen ni se desalienten por causa de mí, sino más bien gócense conmigo,
porque el Señor no solo nos ha tenido por dignos de creer en Su nombre,
sino también de padecer por causa de Él.

Desde la ciudad de Carlisle en Cumberland, el 8vo día del Quinto mes, 1663.

De su obediente hijo,

John Banks.

Un tiempo después,
sentí inclinaciones en mi espíritu de ir a visitar algunos condados vecinos,
como Westmoreland y Lancashire, y cuando me sentí libre de mi deber en aquellos condados,
regresé a la casa de mis padres,
y viví con ellos como un año más. En el 26 del sexto mes, 1664,
tomé a una Amiga llamada Ann Littledale como mi esposa,
en una reunión pública del pueblo de Dios que en desdén es llamado Cuáqueros,
en la casa de un Amigo en Pardshaw town, delante de muchos testigos,
sintiendo libertad en el Señor para hacerlo.
Esto en verdad fue una bendición y una misericordia que recibí de Su mano,
por lo cual siento que es mi deber alabarlo,
y darle todo el honor y la gloria a Aquel que vive para siempre.

Cerca de cuatro años después de haberme casado,
el Señor me llamó a viajar en la obra del ministerio,
e hizo que estuviera dispuesto a dejar todo en respuesta a Sus requerimientos,
y que fuera al sur y al oeste de Inglaterra.
Sí, hizo que estuviera dispuesto a dejar a mi amada esposa y a mi tierna hija,
a pesar de que eran muy importantes y preciadas para mí,
y salí en el poder y Espíritu del Señor Jesús. Nuestro amigo John
Wilkinson de Cumberland y yo viajamos juntos en la obra y servicio
del Señor. Emprendimos nuestro viaje el segundo mes del año 1668,
y entramos a Yorkshire, y ahí visitamos muchas reuniones en varios lugares,
en las cuales teníamos mucho que hacer para el Señor y Su verdad.
Desde Yorkshire viajamos a Nottinghamshire, Leicestershire y Warwickshire,
donde tuvimos muchas reuniones benditas, y donde escribí la siguiente carta a mi esposa.

Querida Esposa,

Con quien estoy verdaderamente unido;
te saludo con cariño en el amor y unidad puros del Espíritu de la Verdad,
en lo cual el Señor nos ha hecho realmente uno,
y te hago saber que estoy bien en todos los aspectos;
bendito y alabado sea el Señor nuestro Dios por siempre.

Desde mi corazón te extiendo una mano; dame la tuya,
y sigamos juntos en la obra y servicio del Señor,
para que así seamos una fortaleza y un aliento el
uno para el otro para continuar en fidelidad,
y llevar un testimonio fiel del Señor en lo que Él requiera de nosotros,
al hacer o padecer,
y al entregar cualquier cosa que tengamos o disfrutemos en este mundo.

Mi amor querido, entrega todo libremente al Señor nuestro Dios,
a fin de que sea ordenado y administrado por Aquel
que es grande en sabiduría y maravilloso en consejo,
y quien debe ser admirado por todos los que verdaderamente lo aman y le temen,
y esperan Su gloriosa aparición de luz y vida.
No te preocupes por mí salvo en el Señor,
porque Él tiene un cuidado especial y tierno de nosotros, y de todo Su pueblo,
siempre y cuando nuestros corazones se mantengan cerca de Él.

El día de hoy fuimos a ver a nuestro querido amigo William Dewsbury,
y tenemos la intención de viajar por el condado, visitando la Semilla de Dios,
en dirección a Bristol, y luego hacer lo que sea que el Señor nos mande.

Así, recordando mi deber con mis padres, y mi amor a los Amigos,
como si hubiera mencionado todos sus nombres, sigo siendo tu querido y amoroso esposo,

J+++.+++ B.

Warwick, el 4to del Cuarto mes, 1668.

La carta que me envió mi esposa.

Querido Esposo,

Después de una larga espera por oír de ti, antes de escribir esto,
he recibido dos cartas, por las cuales me sentí muy satisfecha y refrescada;
pero en la última que me enviaste de Somersetshire,
noté que habías estado sintiendo debilidad corporal por algún tiempo.
Al principio, cuando escuché esto, me entristecí en mi espíritu,
pero considerando la grandeza y suficiencia del amor y poder del Señor,
en quien está nuestra fuerza, me quedé tranquila,
con la esperanza de que todas las cosas ayuden a bien al final.
Querido esposo, he estado,
y todavía estoy muy decaída físicamente debido a una fiebre fuerte,
pero estoy bien internamente,
bendito sea el Señor. Me enfermé un mes antes del último quinto día,
y como en dos semanas después recibí algo de fuerza, pero luego me puse grave otra vez,
y ahora estoy muy débil.
Realmente deseo que esta carta llegue a salvo a tus manos,
para que puedas saber cómo estoy, y para que, en la sabiduría de Dios,
consideres qué puede tender más a la gloria de Dios en este asunto.
En verdad puedo decir, en un sentido del amor y verdad del Señor (según mi medida),
que ya sea que vea tu rostro otra vez o no,
no quiero otra cosa más aparte de que se haga la voluntad de Dios en todas las cosas,
ya sea que vivamos o que muramos; a cuyo cuidado y protección paternal te encomiendo,
y te saludo con cariño, con amor a tu compañero John Wilkinson.
Me despido de ti; y sigo siendo tu querida y amorosa esposa,

Ann Banks

Whinfell-Hall, en Cumberland, el 19 del Quinto mes, 1668.

Desde aquí viajamos hacia el oeste, a través de una parte de Devonshire, y a Dorsetshire,
Hampshire, Wiltshire y luego hasta Londres.
El Señor estaba con nosotros;
y los Amigos fueron grandemente refrescados y consolados con nosotros,
y nosotros con ellos.
En aquellos días, había una actitud muy receptiva y mucha ternura entre los Amigos,
y entre muchas otras personas en el lugar a donde llegamos,
y el testigo de Dios en sus corazones fue alcanzado rápidamente.
Tuvimos reuniones muy grandes y repletas en casi todos los lugares por los que pasamos,
y muchos fueron convencidos de la verdad, quienes todavía viven en ella,
y permanecen como testigos de Dios.
En Londres, escribí las siguientes cartas a mi esposa y a mi aprendiz, Peter Fearon:

Querida Esposa,

Recibí tu carta, por la que me enteré de la gran debilidad en la que has estado,
lo cual ha sido una prueba fuerte y un gran ejercicio para
mí. Pero cuando considero el gran amor de Dios para contigo,
al preservarte en la fe para creer en Él,
y para entregarte a Él con paciencia y verdadero contentamiento en tu gran debilidad,
me he sentido aliviado de mi carga y mi ejercicio ha disminuido.

Espera diariamente a sentir al Señor como tu fortaleza,
en el tiempo de tu mayor debilidad.
Apóyate completamente en Él, confía en Él,
cree en Él y Él nunca te fallará. Él puede ser más para ti que un esposo,
y más para tu hija que su padre.
Mi deseo es que experimentes el incremento de tu porción en Él,
y el aumento de tu herencia, para que puedas morar dentro de los límites de Su santuario,
a la vista de Su glorioso Hijo para siempre,
y también para que puedas sentir el crecimiento de tu fe,
y cómo tu paciencia y satisfacción descansan en Aquel en cuyo poder se experimentan
la seguridad y la preservación. A medida que permanezcamos en Él,
ya sea que vivamos o que muramos, del Señor somos, y siempre nos irá bien.
Y si alcanzamos esto, no importa lo que suframos o soportemos en esta vida.

Recuerda mi afectuoso y tierno amor (y además mi deber) a mis padres;
porque aún encuentro como mi deber ser tierno con ellos,
y hacer por ellos cualquier cosa que esté a mi alcance,
considerando todo lo que ellos han hecho por mí. Te saludo con verdadero amor,
pensando a menudo en nuestra pequeña, y al sentir mucho amor a los Amigos,
y a los parientes y vecinos, sigo siendo tu cariñoso esposo,

J+++.+++ B.

Y ahora Peter Fearon, mi aprendiz: Toma nota,
y presta mucha atención a lo que voy a decirte; ponlo en tu corazón,
y considera bien estas cosas, ahora en mi ausencia.
Mi amor verdadero y sincero está fluyendo hacia ti,
y deseo tu prosperidad y bienestar en todo lo que es bueno,
tanto interna como externamente; pero ante todo, y principalmente,
en eso que pertenece a la salvación de tu alma; el camino a la cual, el Señor,
en Su amor, te ha manifestado en una medida.
Por lo tanto, sé vigilante para que camines en él; es decir,
presta atención a la luz de Cristo Jesús en ti, a la medida del Espíritu de la Verdad,
la cual te guiará a toda verdad y te sacará de todo engaño conforme la obedezcas y sigas.
Deja cualquier cosa que esta luz pura en ti manifieste como malo y te reprenda por ello,
aunque sea algo que ningún ojo pueda ver, ni ningún hombre saber, aun así,
debes abandonarlo,
y esperar y velar diariamente contra ello en la luz que lo pone de manifiesto,
y entonces recibirás poder para echarlo fuera y para separarte de ello.
La luz, que es Cristo Jesús--el camino,
la verdad y la vida--nos enseña a ser sobrios y humildes.
Nos enseña que nuestras palabras deben ser pocas y sazonadas,
y que debemos ser gentiles y amables, no altivos, sino siempre temerosos del Dios vivo.
Esto mantendrá tu corazón limpio conforme permanezcas en la luz,
manteniéndote bajo y humilde en la abnegación,
y estando dispuesto a tomar y llevar la cruz diaria;
y a medida que esta obra avance en el corazón, llegarás, a través de ella,
a apartarte de toda iniquidad.
"`Todas las cosas que son reprobadas son hechas manifiestas por la luz,
porque lo que manifiesta todo, es la luz;`"^
footnote:[Efesios 5:13]
y eso que la luz pone de manifiesto como pecado y maldad, ya sea en palabra o en acción,
debes dejarlo y negarte a ti mismo en ello.
Porque esta es la voluntad y mente del Señor, revelada por Su bendito Espíritu;
y aquel que conoce la voluntad de su señor y no la hace,
según las Escrituras de la verdad, recibirá muchos azotes.^
footnote:[Lucas 12:47-48]

En cuanto a las cosas relacionadas a tu trabajo y servicio,
sé paciente y mantente contento, y ocúpate sosegadamente en tus negocios,
manteniéndote en el temor de Dios.
Y no digas en tu corazón que yo voy a pensar que no has hecho suficiente,
porque estoy lejos de pensar así. Mi único deseo es que en cualquier cosa que hagas,
aunque sea algo muy pequeño, tengas cuidado de hacerlo bien.
Pero, sobre todas las cosas,
mantente verdaderamente dispuesto a servir a tu señora y sé obediente a ella,
porque cualquier cosa que hagas para ella,
la tomaré como si lo hicieras para mí. Y procura conducirte en amor,
y ser un buen ejemplo en mi familia, para que así todos puedan vivir en amor y unidad;
en la cual deseo que el Señor los mantenga a todos ustedes.

Tu afectuoso maestro,

J+++.+++ B.

Desde Whitechapel en Londres, el tercer día del Sexto mes, 1668.

Desde ahí continué con mi viaje hacia el oeste,
pero donde tuve más dificultad fue en Westmorland, y en Hartford cuando llegué a Londres,
y después en Reading, Wycombe, Charlcote, Bristol y a través de Wiltshire,
donde tuve quince reuniones en tres semanas,
en las cuales estuvieron muchas de esas indomables personas de un espíritu divisionista,^
footnote:[La referencia que Banks hace a estas "`personas de espíritu
divisionista`" probablemente se refiera a los seguidores de John Perrot,
que bajo el pretexto de promover una "`dispensación más espiritual`" del Cristianismo,
se opuso a algunos aspectos del orden y disciplina de la Sociedad de Amigos,
y cayó en imaginaciones y libertades carnales.]
aunque ninguno de ellos tuvo poder para oponerse a mí. Sin embargo,
después de casi todas las reuniones ellos se llenaban de ira contra mí a mis espaldas,
y hacían amenazas diciendo lo que harían en la próxima reunión, pero nunca,
en ninguna reunión, tuvieron poder de abrir su boca y oponerse;
porque le plació al Señor estar conmigo de una manera maravillosa.
Esto lo digo con reverencia y humildad ante Él, para Su alabanza y gloria.
Porque mi testimonio era como una llama de fuego entre espinos y cardos,
como muchos del pueblo de Dios podrían testificar.

Mi compañero, Christopher Story, era una ayuda y un consuelo para mí,
y aunque no estaba muy involucrado en esa contienda con los separatistas, aun así,
él sentía una profunda unidad conmigo en el espíritu,
y prestó un buen servicio a los Amigos,
y continuó siendo un hombre serio y lleno de sustancia en la obra del ministerio,
tanto en las zonas cercanas a su hogar como también más allá de ella.

¡Oh!
Grandes fueron las pruebas bajo las cuales viajé muchas veces,
tanto en cuerpo como en espíritu;
porque el peso y la iniquidad del espíritu divisionista estaban fuertemente sobre mí,
pero el poder del Señor lo encadenó y limitó. Tuve muy poca comida y tiempo para dormir,
especialmente en Wiltshire,
porque los que eran de ese espíritu me seguían de una reunión a otra.

La siguiente carta se la escribí a mi hija,
después de que ella comenzó a servir en una casa en Londres, en el año 1682.

Sarah Banks, mi hija mayor,

Tú has sido muy cercana y querida para mí desde el día en que naciste, y,
como un padre muy tierno, he sentido un cuidado piadoso por ti,
de que fueras criada en los primeros y más tiernos años de tu vida para tu preservación;
teniendo en mi corazón muchos deseos al Dios Todopoderoso,
de que a medida que aumentaras tus años,
le placiera hacerte sensible y darte un entendimiento
de esas cosas que contribuyen a tu paz eterna,
y a la salvación de tu alma en el reino de gloria, cuando el tiempo aquí ya no sea más.

Y ahora, querida hija, habiendo el Señor respondido a mis peticiones hasta este punto,
y habiéndome capacitado para ejercer mi cuidado sobre ti,
tengo algo más en mi mente que decirte por el bien de tu alma; lo cual,
si verdaderamente le prestas atención, tenderá a tu bien,
y nunca lo sentirás como un tropiezo para lo que realmente sea necesario para ti.

Primero que nada, quiero recordarte que Dios,
conforme a Su Divina Sabiduría y Providencia, te ha dado vida y aliento,
lo cual debes estimar y valorar como una gran misericordia,
entre muchas más que has recibido de Él. Y tú además has llegado a entender,
en una medida, cómo debe ser tu comportamiento como hija de Dios,
al caminar en la luz y gracia de nuestro Señor Jesucristo,
que Él ha puesto en el secreto de tu corazón como tu maestro en todas las cosas.
Mi interés ahora es despertarte a esto,
recordándotelo para que seas fiel y obediente a sus requerimientos,
ya sean grandes o pequeños.

Esta luz y gracia de nuestro Señor Jesucristo te enseña tu deber para con Dios,
para con tus padres y para con todos los hombres y mujeres.
Primero te enseña a temer y amar a Dios; a esperar en Él,
y a adorarlo y servirlo con toda tu mente y fuerza,
para que únicamente Él (por Su Espíritu manifestado en y
a través de Jesucristo) sea tu principal amor y deleite.
Ella te enseñará (conforme te mantengas velando)
a renunciar a toda impiedad y deseo mundano,
a tomar placer y deleitarte en las reuniones junto al pueblo de Dios,
y a adorarlo a Él en espíritu y verdad,
para que así puedas llegar a tener cada vez más unidad y comunión con Sus hijos fieles,
conforme a tu medida.

Esta luz pura del Hijo de Dios te enseña a ser humilde de corazón,
a ser sobria y vigilante con tus palabras, con tu actitud y con tu comportamiento,
en tu vida y conducta, y a escoger personas que actúen, como compañía, y no a aquellos,
que, aunque profesan la verdad, son ligeros, descuidados y altivos,
los cuales siguen las modas de este mundo, y son chismosos y murmuradores,
y se entrometen en asuntos de otros hombres y mujeres que no les conciernen.
Asegúrate de ocuparte únicamente en eso que te concierne a ti,
y que es apropiado para tu lugar como sirvienta.

Esta es la manera de crecer en la gracia y en el conocimiento que salva,
y de tener el hermoso atavío, el cual es el ornato de un espíritu humilde y apacible,
que es mejor que un atuendo costoso y es de gran estima delante de Dios.
Esta es la forma de ser amada por Dios y por Su pueblo, de crecer como una buena mujer,
y de tener un final bendito y feliz.
Este es el bendito camino y curso de vida que mi alma desea para ti, mi querida hija,
en el que quiero que cuidadosamente vivas y te mantengas, hasta el fin de tus días. Amén.

La luz de Jesucristo, que de esta manera te enseña tu deber para con Dios,
también te enseñará tu deber para con los hombres, mujeres, siervos e hijos,
especialmente ahora en ese lugar, donde eres una sirvienta.
Te enseñará a ser fiel,
servicial y obediente a tu maestro y a tu señora
en todas las cosas que sean apropiadas y correctas,
a tener cuidado de que nada que te haya sido confiado sea desperdiciado,
y a velar con un ojo que procura el bien de todos en la familia en la que sirves.
Si ves algo que está mal, no se lo digas a nadie que no le concierna,
porque esto puede causar disensión; sino que primero díselo al individuo en amor,
porque así te gustaría que hicieran contigo.
Esto es conforme a la ley justa de Dios, la cual es luz,
y nos enseña a hacer a todos como quisiéramos que nos hicieran a nosotros.
Y cuando algo malo suceda contigo,
y alguien hable contigo y te reprenda por ello (así
como Pablo aconsejó a Tito respecto a los siervos),
te exhortó en ternura a que no murmures, ni respondas,
salvo para decir que el error será enmendado.

Mi querida hija, el deseo de mi corazón al Dios Todopoderoso,
es que este consejo y recomendación tenga efecto sobre ti, y que,
en una seria consideración de este, con deseos honestos surgiendo en ti para cumplirlo,
tu corazón sea verdaderamente quebrantado y enternecido delante del Señor,
y así te mantengas en toda mansedumbre y humildad ante Él,
hasta el fin de tus días. Amén.

Esta es la oración de tu tierno y afectuoso padre,

John Banks.

Este año fui a Irlanda otra vez, desde donde escribí la siguiente carta a mi esposa:

Querida Esposa,

En eso que abre mi corazón al Señor, y me enternece verdaderamente delante de Él,
me siento en este tiempo ensanchado con ternura hacia ti,
junto con nuestros queridos hijos y siervos,
rogándole al Señor que sus corazones se mantengan
abiertos y tiernos delante Dios por este mismo poder,
para que puedan crecer cada día más,
y así tengamos un sentido de la condición de cada uno,
de nuestro crecimiento juntos mediante la virtud viva que brota de la Raíz que nos sostiene.
Porque mientras que nuestra habitación y morada se encuentre aquí en la Raíz,
aunque nuestra labor y servicio no sean el mismo,
debido a la diversidad de dones que se nos han dado, aun así,
creceremos juntos como lo hacen todos los fieles en Cristo Jesús.

Que el Señor te preserve en Su temor, y te guíe en Su sabiduría,
para que puedas ser un buen ejemplo delante de tus hijos y siervos,
teniendo cuidado de educarlos en ese mismo temor,
para que caminen conforme a la verdad en todas las cosas,
siempre teniendo un cuidado tierno sobre ellos, principalmente por el bien de sus almas,
como también de sus cuerpos;
porque tú tienes muchas oportunidades en las que puedes hacerles bien,
las cuales yo no tengo.
Por lo tanto, querida mía, preocúpate por su bien conforme crecen en entendimiento,
porque ellos son listos e inteligentes,
y se dan cuenta rápidamente si somos indulgentes con ellos
en alguna cosa en la que no deberíamos serlo.
Y si somos indulgentes con ellos, perderemos nuestro dominio y autoridad sobre ellos.
Procuremos que nuestro cuidado alcance al Testigo de Dios en ellos, es decir,
el Testigo de Su buen Espíritu,
del cual la mayoría de ellos ha llegado a tener cierta experiencia,
y por el cual saben qué deben hacer, y qué no deben hacer.
Y a medida que este Testigo se levante en ellos y sea atendido, los hará buenos niños;
pero mucho depende del ejemplo que les demos.

Por esta razón,
siento una responsabilidad cada vez más grande con
respecto a cómo debo conducirme con ellos,
a fin de que pueda quedar libre de mi obligación y deber en lo concerniente a ellos,
especialmente por el bien de sus almas.
El Señor nos ha bendecido grandemente con ellos como muestra de Su gran misericordia,
pero todavía tenemos que mantener un gran cuidado y responsabilidad por nuestros hijos;
porque he visto claramente que, por la falta de esto,
muchos hijos que podrían haberle dado honor a Dios, a Su verdad y a sus padres, más bien,
han deshonrado a todos, aunque puede que tengan muchas posesiones en la tierra,
y abundancia, comodidad y mucha reputación (así llamada).
Porque de qué sirven estas cosas si han perdido la Verdad,
independientemente de que muchas personas tengan su mirada puesta en ellas,
y menosprecien las cosas más importantes, que deberían ser su mayor interés.

Y ahora, queridos hijos,
ya pueden entender algo de nuestro cuidado y responsabilidad por ustedes.
Ustedes que han llegado a este entendimiento, los exhorto como un padre tierno,
en el amor del Señor, a que tomen para ustedes esta determinación piadosa, y digan:
"`¿Cómo debo proceder en todas las cosas;
cómo debo conducirme y comportarme (tanto en palabra como
en acciones) para ser un hijo obediente a mis queridos padres,
que tienen este cuidado sobre mí para mi bien y para mi preservación en todos los sentidos,
y especialmente con mi madre, debido a la ausencia de mi padre?`"
Y a fin de que puedan comportarse de esta manera,
tanto ahora con ella como conmigo cuando esté presente,
que todos estén sujetos unos a otros, y sean condescendientes los uno con los otros.
Vivan en amor, quietud, y buena voluntad los unos para con los otros;
y manténganse sobrios en el temor de Dios,
evitando toda compañía de personas que no sean serias.

Y de ninguna manera estén ociosos en ningún momento,
sino que dedíquense a algún buen servicio,
uno que sus cuerpos y entendimiento sean capaces de realizar,
con una mente dispuesta y resuelta a ayudar a su madre en sus asuntos.
Y sean cuidadosos en leer sus libros cuando tengan tiempo para ello.
Lean las Sagradas Escrituras, y los libros de los Amigos,
y sean diligentes en su camino y orden para asistir a las reuniones,
tanto las de los días
de semana como la de los primeros días,
para que así la labor de sus manos se haga más fácil, dulce y confortable para ustedes,
y para que Dios tenga la alabanza,
el honor y la gloria por todas Sus bendiciones y misericordias,
quien es digno eternamente.

Peter Fearon, quien fue mi siervo por siete años,
ahora es mi fiel compañero en la obra del Evangelio.

Mountmellick en Irlanda, el veintitrés del Cuarto mes, 1682.

Al principio del segundo mes del año 1684,
fui encarcelado a demanda del mencionado George Fletcher, encargado de la parroquia,
debido a que por causa de conciencia no pude hacer otra cosa más
que dar mi testimonio contra esa gran opresión de diezmos;
siendo primero citado, y luego arrestado,
porque en obediencia al mandamiento de Cristo no pude responder con juramento
a su declaración. En el mismo día que fui puesto en prisión,
llegaron doce hombres con una orden de parte de George Fletcher,
los cuales se apoderaron de mis bienes y se llevaron
lo equivalente a siete libras y diez chelines,
como parte de una multa de veinte libras por un Amigo en el ministerio que habló en
nuestro lugar de reunión en Pardsay-Crag (esto fue en el tiempo en el que estaba vigente
el acta penal contra "`reuniones secretas.`") Los bienes fueron vendidos por él,
o por su orden, y muchos más les quitaron a otros amigos por dicha multa,
que en total alcanzaba las treinta y cinco libras.

Mi encarcelamiento continuó por seis años y nueve meses,
hasta que quedé en libertad por el Acta de Gracia del Rey William.^
footnote:[En Mayo de 1690, un año después de que William III obtuviera el poder,
él declaró un perdón general para una gran cantidad de prisioneros políticos y religiosos.]

Lo siguiente es un relato verídico de los abusos y la crueldad que yo mismo y
algunos de mis compañeros de prisión sufrimos de parte del carcelero,
George Lancake, y del guardia encargado, Alexander Richardson,
por ninguna otra razón más que adorar a Dios en nuestra celda, y, en obediencia al Señor,
hablar en Su nombre en exhortación y oración,
y algunas veces por amonestar a las personas cuando
pasaban por la ventana de nuestra celda,
con la intención de que se volvieran al Señor a través de
un pronto arrepentimiento y corrección de sus caminos.

En el veinteavo día del quinto mes, 1684, un poquito antes de nuestra reunión,
estando otros cinco amigos prisioneros conmigo, el carcelero me dijo:
"`A menos de que me prometas que no vas a predicar hoy, te sacaré a otro lugar.`"
Yo respondí: "`No puedo hacer una promesa así,
ni tampoco sé antes de que llegue el momento si voy a predicar o no.`"
"`Entonces,`" dijo él, "`he preparado otro lugar para ti.`"
Me tomó por el brazo, y me llevó y me metió en una celda apestosa, llena de humo,
debajo de la cual fabricaban cerveza, y me encerró en ella,
donde estuve tres días y dos noches, sin cama.

El primer día en la noche, después de haber sido puesto en ese lugar,
vino el guardia y abrió la puerta, y dijo:
"`Mi amo me ha enviado a decirte que salgas y vayas a tus amigos.`"
Pero yo le respondí: "`Ve y dile a tu amo, que no saldré de este lugar a ningún otro,
hasta que el que me metió aquí me saque él mismo.`"^
footnote:[Por lo que ocurre a continuación,
parece que a John Banks se le dio a entender que
el carcelero le estaba tendiendo una trampa,
buscando motivos para culparlo de escaparse de ahí por sí mismo.]
Él fue y le dijo, y el carcelero le ordenó a su siervo decirme lo siguiente:
"`Dile que él se quedará ahí hasta que se pudra,
pero yo no iré por él.`" Pero no le presté atención a eso, sabiendo bien lo que hice.
En ese entonces, había varios presos en su casa por deudas,
quienes habían malgastado la mayor parte de sus bienes,
los cuales entonces le decían al carcelero:
"`El Cuáquero dice que no saldrá hasta que tú vayas y lo saques,
y tú dices que él se quedará ahí hasta que se pudra pero que tú no irás a sacarlo,
¡ya veremos quién obtendrá la victoria!`"

Pasó esa noche y el siguiente día y noche,
y en el tercer día al anochecer vino el guardia,
y me dijo que su amo lo había enviado a sacarme a la fuerza,
si yo no quería salir voluntariamente, siendo esta la cuarta vez que lo enviaba.
El guardia era un hombre corpulento, fuerte y con una actitud ruda.
Estando sentado, me levanté y me puse frente a él, y le dije:
"`Si tú puedes sacarme a la fuerza, hazlo, aquí estoy,`" y extendí mis brazos.
Entonces me agarró por un brazo y me haló con todas sus fuerzas,
pero no pudo moverme en lo absoluto, y entonces dijo impíamente: "`Dios me bendiga,
me parece que el diablo está en este hombre ¡no puedo moverlo!`"
"`No,`" dije yo,
"`el diablo está en ti,
y yo a través del poder de Dios soy más fuerte que tú y que el diablo.
Ve y dile eso a tu amo.`"

Durante todo ese tiempo sentía que su amo estaba atormentado,
siendo turbado en su conciencia tanto de día como de noche,
como luego él confesó. Entonces el guardia fue y le dijo lo que había hecho,
y lo que yo dije, y entonces dijo: "`Me parece que él es tan fuerte como veinte hombres,
porque no pude moverlo ni un poquito; fue como sí hubiera tratado de mover un árbol.`"
Pero un poco tiempo después el carcelero mismo vino y dijo: "`¿Ahora qué John?
¿Cuál es la razón por la que no quieres salir?
Te he enviado a mi siervo muchas veces para dejarte ir a tus amigos.`"
Yo respondí: "`Porque fue tu voluntad y deseo traerme hasta aquí,
así que tú también deberás llevarme de regreso otra vez,
o aquí me quedaré. Seré un prisionero fiel para ti, no intentaré escaparme.`"
Después de algunas palabras más entre nosotros, me tomó por el brazo, diciendo: "`Bueno,
ven entonces, si no hay otra manera, yo te llevaré de regreso;`" lo cual hizo,
bajándome por las escaleras a través del patio,
y llevándome a la puerta de la cual me sacó, y luego, echándome adentro, dijo:
"`Aléjate de mí, ojalá que nunca hubiera visto tu rostro.`"
Entonces los prisioneros por deudas que estaban parados
en su puerta nos miraron y se rieron,
y dijeron: "`¡El Cuáquero obtuvo la victoria!`"

Después de esto, durante siete reuniones seguidas,
el guardia me arrastró hasta la casa del carcelero,
siendo presionado por él con muchas amenazas,
ordenándole a su siervo que no dejara que ninguno
de nosotros saliera por la puerta de su patio.

En el 13vo día del séptimo mes,
nuestro amigo Peter Fearon vino a visitarnos cuando todavía éramos prisioneros.
Nos sentamos juntos a esperar en el Señor,
y después de un poco de tiempo Peter Fearon empezó a orar.
Pero el guardia entró de repente con mucha ira, y le preguntó a nuestro amigo:
"`¿De dónde vienes tú? ¡Sal de aquí!`" Y entonces
comenzó a halarlo de la manera más cruel,
tomándolo por la bufanda y lanzándolo a una cama,
diciendo que lo colgaría o le arrancaría su garganta.
Él seguía sacudiéndolo y jalándolo por su bufanda,^
footnote:[Una especie de pañuelo que usaban alrededor del cuello.]
arrastrándolo fuera de la puerta y llevándolo a la casa del carcelero
maldiciéndolo y haciendo juramentos sobre lo que le haría. Yo reprendí
duramente tanto al carcelero como al guardia por esto,
y un poco después lo dejaron ir.
En ese día le escribí a mi esposa e hijos la siguiente carta.

Querida Esposa,

Realmente eres querida para mí--tan cercana a mí que somos en verdad uno,
para ayudarnos a llevar las cargas de cada uno,
para tener el mismo sentir y estar verdaderamente
interesados por la preservación de cada uno,
tanto en la casa como fuera de ella, en prisión o en libertad, en enfermedad o salud;
y no sólo por el cuerpo, sino por la felicidad y bienestar eterno del alma.
Este es el verdadero deber de un esposo y una esposa que están verdaderamente unidos,
y que han llegado a experimentar el verdadero matrimonio que es juntado por Dios.
Oh, cómo esto me ayuda y me fortalece, me anima y me mantiene,
en los momentos de más grandes pruebas.

Y ahora, querida mía, en cuanto a mi condición actual de sufrimiento, estoy bien, porque,
aunque físicamente no esté del todo bien, aun así, en el tiempo del Señor espero estarlo.
Yo digo que estoy bien, aunque mi condición sea esta;
porque estoy muy seguro de que esto es conforme a Su voluntad,
y por hacer Su voluntad siento mucha paz y satisfacción,
aunque la ira y la crueldad de los hombres impíos siguen muy inclinadas
contra mí. Pero creo que no pasará mucho tiempo hasta que el Señor,
por Su poder, los derribe; porque veo, en la luz del Señor,
que la fuerza de ellos se debilita y que su expectativa respecto a mí comienza a desmayar.
Sin embargo, cualquier cosa que el Señor aún les permita infligir sobre mi cuerpo,
considero todo lo que tenga que soportar o atravesar aquí como una leve tribulación,
debido a la evidencia y certeza de ese más excelente
y eterno peso de gloria que tengo en la mira,
a través de la fe en Jesucristo,
y sé que estoy viajando por el camino que me llevará a la herencia eterna.

Y, por lo tanto, querida mía,
sigamos resuelta y fielmente esas cosas que conducen
a nuestra paz y gozo eternos con el Señor,
por las cuales podemos tener la certeza plena de la salvación
de nuestras almas en el reino de felicidad y gloria,
cuando el tiempo aquí deje de ser,
independientemente de cualquier otra cosa que podamos disfrutar de este mundo,
ya sea mucho o poco.
El Señor da y quita, o permite que sea así, según Su buena voluntad y placer,
bendito sea Su santo nombre, y honrado sea Su glorioso poder, ahora y para siempre ¡Amén!

Y ahora, mis queridos hijos, por quienes mi corazón a menudo se enternece,
mi corazón anhela que sean preservados del mal,
y que puedan crecer e incrementarse en todo lo que es bueno.
Le pido a cada uno de ustedes que incline su oído,
y preste mucha atención a lo que tengo que decirles.

John, mi hijo, y querido niño: Dios en Su amor, según Su sabiduría Divina,
te ha dado una medida o manifestación de Su buen Espíritu, gracia, o luz,
la cual Él ha puesto en tu corazón y conciencia como
un testigo contra toda especie de mal.
De esto, en alguna medida, has llegado a tener conocimiento;
mediante lo cual tú sabes que debes hacer eso que es bueno,
y apartarte de todo lo que es malo.
Esta luz del Señor Jesucristo te enseña a no ser desenfrenado o descuidado,
o dado a conversaciones ociosas o a palabras vanas;
y si tú obras o actúas de manera contraria a esta luz pura,
ella te reprenderá y juzgará por ello.
Esto es eso, mi querido hijo, que debes atender y amar,
y entonces no solo te descubrirá todo pecado y cada mal,
sino que a medida que prestes atención a sus correcciones,
reprensiones y manifestaciones,
recibirás poder sobre esas cosas que la luz te manifiesta, una tras otra,
y te mantendrá apartado de toda compañía vana y ligera,
a fin de que mantengas tu mente en el temor de Dios para
así servirle a Él. Sobre todas las cosas ama la verdad,
y a aquellos que están en ella.
Y ama asistir a las reuniones de los Amigos, y deléitate en su compañía;
porque así llegarás a ser separado de toda especie de mal, y a ser sobrio y serio,
como es apropiado en la verdad.
Este es tu deber para con Dios, procura ser hallado caminando en él;
y a medida que te encuentres haciendo esto,
la luz y gracia pura de nuestro Señor Jesucristo, que te enseña tu deber para con Dios,
y cómo obedecerlo, también te enseñará tu deber para con tus padres,
y en especial para con tu querida madre, y también para con tus hermanas y hermano.
Puesto que tú eres el mayor en la casa, espero que seas cuidadoso y diligente en esto,
manteniendo el amor y la ternura hacia tu querida madre,
para que así puedas ser una fortaleza y ayuda para ella ahora en mi ausencia.
Te exhorto a que procures esto, así como esperas la bendición del Señor,
y mi favor y aprobación. También ten cuidado de que no haya contienda entre tus hermanas,
hermano y tú en ningún momento, ni en palabras ni en acciones;
sino que sean tiernos y amoroso el uno con el otro.

Y ahora ustedes Ann y Mary, mis hijas y queridas niñas, a quienes amo mucho,
junto con todos los demás: asegúrense de no hablar mal la una de la otra,
y de no hacerle daño a nadie.
No lleven historias de una casa a otra, y cuando sean enviadas a hacer un encargo,
vayan y regresen rápido.
Sean amorosas, amables, y respetuosas la una con la otra, y con su hermano,
hermana y sirvientes, y ayúdense una a otra de buena gana en todas las cosas,
pero especialmente ayuden a su querida madre.
Sean hacendosas y obedientes a ella en todas las cosas que ella les mande a hacer;
las exhorto a que lo hagan con prontitud y disposición, sin murmurar.
Mis queridas hijas, mantengan estas mis palabras en su mente cada día,
para que todos puedan servirse el uno al otro en amor.

Y a ustedes, pequeños William y Emme, los menores.
Mis queridos hijos, asegúrense de amarse el uno al otro;
no se aparten del camino cuando vayan a la escuela, o cuando regresen a casa.
No le hagan daño a nadie, y ocúpense en sus libros para que puedan ser buenos estudiantes.
Asegúrense de recordar lo que les digo,
y sobre todas las cosas procuren hacer lo que su madre les mande,
y amar a su hermano y hermanas.
Queridos hijos, todos ustedes ocúpense en sus libros; lean las Sagradas Escrituras;
y que el Señor los bendiga y preserve a todos en amor, unidad, paz y quietud, temiendo,
sirviendo y amando a Dios con todo su corazón, y entonces todo estará bien.

Siento mi cuerpo muy alterado, debido a la crueldad y abuso del carcelero y su guardia,
junto con la carencia de aire fresco;
porque no he tenido ninguna libertad para caminar afuera estos últimos meses.
El carcelero no me permite hablar u orar en ninguna reunión una vez que escucha mi voz;
por lo cual, el Señor sin duda lo alcanzará con Sus juicios.

Sigo siendo tu amoroso esposo, mi querida esposa, y su tierno padre, mis queridos hijos,

John Banks

Desde mi celda, en Carlisle, el 13vo del Séptimo mes, 1684.

En el 15vo del mismo mes, en la noche,
el carcelero vino y nos mandó a Thomas Hall y a mí a la cárcel común,
porque no podíamos ceder a sus irrazonables demandas; sin embargo,
no había espacio en la cárcel común,
porque estaba completamente llena de pobres deudores y ladrones.
Yo habiendo estado enfermo por un tiempo, y sin todavía estar bien recuperado,
un Amigo le dijo al carcelero: "`Si nuestro amigo muere por tu crueldad y abuso,
su sangre será demandada de tus manos.`"
Él respondió: "`A mí no me importa si él nunca se vuelve a poner de pie;
yo lo pondré en la cárcel común.`" Yo le pregunté:
"`¿Es ese lugar adecuado para que nosotros seamos puestos en él, especialmente yo,
que no estoy bien?`"
Él dijo: "`Es lo que tengo para ustedes, y pueden sentarse o acostarse como puedan;
y si no hay espacio para que se acuesten uno al lado del otro,
pueden acostarse uno encima del otro; y si no hay espacio en ningún lugar,
pueden ir al pozo,`" que era un hueco asqueroso y apestoso, lleno de excremento y paja;
lo cual cumple ese dicho: "`Las misericordias de los impíos son crueles.`"^
footnote:[Proverbios 12:10 Traducción Literal del Inglés]

Entonces, nos puso a los dos entre los deudores en la cárcel común,
donde no había espacio ni para sentarse ni para acostarse,
y fuimos obligados a sentarnos toda la noche junto
al pozo con las ropas que teníamos puestas.
Pero el siguiente día el carcelero sacó a uno de
los pobres deudores y lo puso en su casa,
donde él moraba.
Entonces tomamos algo de paja y sábanas para acostarnos en el suelo,
en el lugar del deudor, el cual era muy sucio y húmedo,
y tomamos piedras para la base de la cama (para la cabecera y la parte de abajo),
y por trece días y noches estuvimos encerrados juntos ahí casi todo el tiempo.
Pero a pesar de la debilidad que tenía cuando fui puesto ahí, y lo inmundo del lugar,
al Señor le plació convertirlo en un lugar de recuperación
y restauración de salud y fuerza para mí;
de modo que cuando el carcelero me tomó de ese lugar otra vez,
e iba bajando por la calle en dirección al lugar del cual me había sacado,
varias personas salieron para verme y dijeron:
"`Se ve mejor que cuando fue puesto en la cárcel
común,`"--lo cual fue causa de gozo para mí;
¡alabanzas, honor y gloria sean dados al Dios Altísimo,
quien por Su propio poder sanador, restaurador y preservador,
puede hacer que suceda cualquier cosa que parezca buena ante Sus ojos!

Una cosa más que es apropiada mencionar,
para demostrar la crueldad y dureza del carcelero.
Mi querida esposa, con otros Amigos,
vinieron a visitarme durante el tiempo en el que estaba en la cárcel común,
lo cual era un viaje de más de veinte millas desde mi casa.
Ella le pidió al carcelero que, si fuera tan amable,
me permitiera salir de la cárcel común, y estar con ella en algún otro lugar.
Pero no habiendo compasión en él, no estaba dispuesto a permitirme salir a ella;
sino que mandó decir por medio de su guardia que, si ella deseaba estar conmigo,
lo podría hacer en la cárcel común, pero en ningún otro lugar.
Y así lo hizo ella, quedándose conmigo alegremente hasta el siguiente día,
en lugar de dejarme y quedarse en un mejor lugar.

En una oportunidad, cuando estaba haciendo un trabajo en la cárcel común,
el carcelero vino a mí y me dijo burlonamente: "`John,
apenas tienes suficiente luz para ver tu trabajo,`" (pues había muy poca luz en la prisión),
"`pero ¿cuál es el problema?`"
dijo él, "`tienes suficiente luz en tu interior.`"
Yo respondí: "`Sí, bendito sea para siempre el Señor mi Dios,
porque tengo suficiente luz; pero tú tienes muy poca, porque si tuvieras más,
verías tu camino y sabrías mejor qué hacer de lo que sabes ahora.`"
Entonces se apartó de mí y no me dijo más nada, pero tomó a mi compañero de prisión,
Thomas Hall, y lo llevó lejos de mí al final de los trece días,
y me dejó ahí tres días y noches más, y luego me sacó como dije antes.

[.asterism]
'''

Como se mencionó anteriormente, John Banks siguió siendo prisionero por casi siete años,
pero finalmente obtuvo su libertad por un acta del Rey William III en 1690.
Su esposa murió un año después de su libertad,
y acerca de este doloroso acontecimiento él escribió lo siguiente:
"`Aunque nuestra separación por su muerte fue la prueba más grande que he tenido,
aun así, el Señor en quien tengo mi confianza fue y es mi preservador,
tanto en esa como en muchas otras intensas pruebas y tratos;
y me siento profundamente obligado en toda humildad a alabarlo, y a devolverle a Aquel,
que es Dios sobretodo, el honor y la gloria;
bendito para siempre ¡Amén!`" Él siguió siendo un
siervo fiel y un ministro útil en el cuerpo de Cristo,
viajando y fortaleciendo la iglesia durante los siguientes veinte años,
como el resto de su diario relata con cierto detalle.
Unas pocas horas antes de su muerte, les dijo a aquellos que estaban con él:
"`Me siento bien, y estoy seguro de que estaré bien;
no tengo nada más que hacer salvo morir, y terminaré en la verdad,
así como comencé.`" Él estaba muy sensible al final,
y después de una vida dedicada al progreso del reino de Jesucristo, murió en paz,
el 6to del octavo mes, 1710, teniendo setenta y tres años.
